### PR TITLE
remove root label extension

### PR DESCRIPTION
**Pull request by hiroshi-matsuda-rit**

### CODE REVIEW

**Comment by dseddah** [comment]
Hi,
if you wrote a converter script to spacy's json format, would you mind sharing it?

Thanks,
Djamé

**Comment by hiroshi-matsuda-rit** [comment]
@dseddah I implemented that json converter in GiNZA because it requires re-tokenization. I'm going to publish it from GiNZA's repository. Thanks,

**Comment by dseddah** [comment]
Thanks.
I assume GiNZA refers to this project?

https://github.com/megagonlabs/ginza

Best,
Djamé

**Comment by hiroshi-matsuda-rit** [comment]
Sure. This is it!
https://github.com/megagonlabs/ginza/blob/feature/refactor_with_entry_points/ginza_util/conllu_to_json.py

**Comment by dseddah** [comment]
Thanks !

**Pull request closed without merging**
